# Default values for chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
environment: # required, no default
az:          # required, no default
image:
  repository: so0k/kuar-inspector
  tag: 1.0.0
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80

ingress:
  # Used to create Ingress record and set up DNS
  hosts:
    - devops-singapore-example.honestbee.com
  annotations:
    kubernetes.io/ingress.class: "nginx"
resources: 
  limits:
    cpu: "100m"
    memory: "128Mi"
  requests:
    cpu: "100m"
    memory: "128Mi"
