kind: SecretClaim
apiVersion: vaultproject.io/v1
metadata:
  name: {{ template "chart.fullname" . }}
  labels:
    app: {{ template "chart.name" . }}
    chart: {{ template "chart.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: Opaque
  path: "secret/{{ required "Environment is required" .Values.environment }}/{{ .Release.Name }}"
  renew: 3900
